apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eksworkshop-eksctl
  region: 'us-east-1'
  version: '1.20'
availabilityZones:
  - 'us-east-1a'
  - 'us-east-1b'
  - 'us-east-1c'
managedNodeGroups:
  - name: nodegroup
    instanceType: t2.small
    desiredCapacity: 3
    ssh:
      allow: true
      publicKeyName: myfirstec2keypair